language: python
python:
  - 3.6
install:
  - pip install pip -U
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  pytest -vv -s
after_success:
  coveralls
git:
  submodules: false

